### ISSUE TITLE
Bug with the function normalize

### ISSUE THREAD

**Issue by phcoutinho** [e-controls/Sim3Tanks#3]
I recently found a bug. Just after performing a simulation with the Sim3Tanks, I noticed that the function "normalize" native from Matlab crashes.

**Comment by arllemfarias** [comment]
Hello @phcoutinho thanks for your comment. Currently we are reviewing this project and working on a new Sim3Tanks structure to solve some problems and improve its usability. As soon as possible, it will be available here on GitHub.
